// Starter quiz templates — pre-filled question banks per cyber category.
// Each template scaffolds a new Quiz so admins can quickly add challenges to learning rooms.
// Questions use the Quiz entity schema: { question, options[], correct_index, explanation, points }

export const QUIZ_TEMPLATES = [
  {
    key: 'linux-fundamentals',
    title: 'Linux Fundamentals Challenge',
    description: 'Core Linux commands, permissions, and navigation basics.',
    category: 'linux',
    difficulty: 'easy',
    time_limit_minutes: 10,
    pass_threshold: 70,
    questions: [
      {
        question: 'Which command lists all files (including hidden) with details?',
        options: ['ls -l', 'ls -a', 'ls -la', 'ls -lh'],
        correct_index: 2,
        explanation: '`ls -la` combines long listing (-l) with hidden files (-a).',
        points: 10,
      },
      {
        question: 'Which permission value represents read + execute but NOT write?',
        options: ['6', '5', '7', '4'],
        correct_index: 1,
        explanation: 'r-x = 4 (read) + 1 (execute) = 5.',
        points: 10,
      },
      {
        question: 'What does `chmod u+s` do to a binary?',
        options: ['Removes the SUID bit', 'Sets the SUID bit', 'Makes it read-only', 'Sets the sticky bit'],
        correct_index: 1,
        explanation: 'u+s sets SUID so the binary runs as the file owner.',
        points: 15,
      },
      {
        question: 'Which file stores user account entries on Linux?',
        options: ['/etc/group', '/etc/shadow', '/etc/passwd', '/etc/login.defs'],
        correct_index: 2,
        explanation: '/etc/passwd holds user entries; /etc/shadow holds password hashes.',
        points: 10,
      },
      {
        question: 'Which command finds files with the SUID bit set?',
        options: ['find / -perm -4000', 'find / -name suid', 'ls -R / | grep suid', 'locate suid'],
        correct_index: 0,
        explanation: 'perm -4000 matches SUID-set files.',
        points: 15,
      },
    ],
  },
  {
    key: 'web-hacking-basics',
    title: 'Web App Hacking Basics',
    description: 'OWASP Top 10, injection, and common web vulnerabilities.',
    category: 'web_hacking',
    difficulty: 'medium',
    time_limit_minutes: 12,
    pass_threshold: 70,
    questions: [
      {
        question: 'Which payload is a classic SQL injection authentication bypass?',
        options: ['<script>alert(1)</script>', "' OR '1'='1' --", '../../etc/passwd', '{{7*7}}'],
        correct_index: 1,
        explanation: "' OR '1'='1' -- always-true condition bypasses login.",
        points: 10,
      },
      {
        question: 'What header helps mitigate reflected XSS in modern browsers?',
        options: ['X-Frame-Options', 'Content-Security-Policy', 'Strict-Transport-Security', 'X-Powered-By'],
        correct_index: 1,
        explanation: 'CSP restricts script sources, mitigating XSS.',
        points: 10,
      },
      {
        question: 'Which attack reads local files via a user-controlled path?',
        options: ['SSRF', 'LFI', 'XSS', 'CSRF'],
        correct_index: 1,
        explanation: 'Local File Inclusion reads files through path traversal.',
        points: 15,
      },
      {
        question: 'What is IDOR?',
        options: [
          'Injection of dangerous objects',
          'Insecure Direct Object Reference',
          'Identity denial of remote',
          'Input data overflow risk',
        ],
        correct_index: 1,
        explanation: 'IDOR exposes objects by predictable identifiers without authorization checks.',
        points: 15,
      },
      {
        question: 'Which tool is best suited for intercepting HTTP traffic in a proxy?',
        options: ['Nmap', 'Burp Suite', 'John the Ripper', 'Hashcat'],
        correct_index: 1,
        explanation: 'Burp Suite is a web proxy for intercepting/modifying HTTP requests.',
        points: 10,
      },
    ],
  },
  {
    key: 'windows-ad',
    title: 'Windows & Active Directory',
    description: 'AD enumeration, Kerberos attacks, and Windows privilege escalation.',
    category: 'windows',
    difficulty: 'hard',
    time_limit_minutes: 15,
    pass_threshold: 70,
    questions: [
      {
        question: 'Which attack reuses a stolen ticket-granting ticket to access services?',
        options: ['Pass-the-Hash', 'Kerberoasting', 'Golden Ticket', 'DCSync'],
        correct_index: 2,
        explanation: 'A Golden Ticket is a forged TGT using the krbtgt hash.',
        points: 15,
      },
      {
        question: 'Which tool dumps NTLM hashes from memory (LSASS)?',
        options: ['mimikatz', 'responder', 'impacket', 'bloodhound'],
        correct_index: 0,
        explanation: 'mimikatz extracts credentials from LSASS.',
        points: 10,
      },
      {
        question: 'What does Bloodhound primarily map?',
        options: ['Network ports', 'AD trust relationships & attack paths', 'Disk usage', 'DNS records'],
        correct_index: 1,
        explanation: 'Bloodhound graphs Active Directory relationships to find attack paths.',
        points: 15,
      },
      {
        question: 'Which DCSync permission is required to replicate credentials?',
        options: ['DS-Replication-Get-Changes', 'WriteDacl', 'GenericAll', 'ForceChangePassword'],
        correct_index: 0,
        explanation: 'DS-Replication-Get-Changes (and -All) permits DCSync.',
        points: 15,
      },
      {
        question: 'AS-REP Roasting targets accounts with which setting?',
        options: [
          'Smart card required',
          'Do not require Kerberos preauthentication',
          'Password never expires',
          'Account disabled',
        ],
        correct_index: 1,
        explanation: 'Accounts without preauth return crackable AS-REP hashes.',
        points: 15,
      },
    ],
  },
  {
    key: 'networking',
    title: 'Network Pentesting Challenge',
    description: 'Scanning, enumeration, and protocol-level attacks.',
    category: 'networking',
    difficulty: 'medium',
    time_limit_minutes: 12,
    pass_threshold: 70,
    questions: [
      {
        question: 'Which Nmap flag enables service/version detection?',
        options: ['-sS', '-sV', '-O', '-A'],
        correct_index: 1,
        explanation: '-sV probes open ports for service/version; -A combines several.',
        points: 10,
      },
      {
        question: 'Which scan type is stealthy and sends only SYN packets?',
        options: ['TCP Connect (-sT)', 'SYN scan (-sS)', 'FIN scan (-sF)', 'Ping scan (-sn)'],
        correct_index: 1,
        explanation: '-sS is a half-open SYN scan, stealthier than a full connect.',
        points: 15,
      },
      {
        question: 'On which port does SMB commonly listen?',
        options: ['22', '80', '445', '3389'],
        correct_index: 2,
        explanation: 'SMB over TCP runs on port 445.',
        points: 10,
      },
      {
        question: 'Which protocol is vulnerable to relay attacks captured by Responder?',
        options: ['HTTPS', 'LLMNR/NBT-NS', 'SSH', 'DNS-over-TLS'],
        correct_index: 1,
        explanation: 'Responder poisons LLMNR/NBT-NS to capture/relay NTLMv2 hashes.',
        points: 15,
      },
      {
        question: 'What does `-sn` do in Nmap?',
        options: ['Scan no ports (host discovery only)', 'Scan all ports', 'Enable stealth', 'Trace route'],
        correct_index: 0,
        explanation: '-sn disables port scan, performing host discovery only.',
        points: 10,
      },
    ],
  },
  {
    key: 'privilege-escalation',
    title: 'Privilege Escalation Challenge',
    description: 'Linux/Windows privesc techniques and misconfiguration hunting.',
    category: 'privilege_escalation',
    difficulty: 'hard',
    time_limit_minutes: 15,
    pass_threshold: 70,
    questions: [
      {
        question: 'Which sudo entry allows running a command as root with no password?',
        options: ['user ALL=(ALL:ALL) ALL', 'user ALL=(ALL) NOPASSWD: /bin/bash', 'user ALL=NOPASSWD', 'user root=/bin/bash'],
        correct_index: 1,
        explanation: 'NOPASSWD removes the password prompt for the listed command.',
        points: 15,
      },
      {
        question: 'A writable PATH script with SUID root is best exploited by?',
        options: [
          'Reading /etc/shadow directly',
          'Replacing it with a payload that runs as root',
          'Changing its permissions',
          'Deleting it',
        ],
        correct_index: 1,
        explanation: 'SUID root execution runs your code as the owner (root).',
        points: 15,
      },
      {
        question: 'Which Windows kernel driver class is commonly abused for privesc?',
        options: ['Print spooler', 'Vulnerable signed drivers (BYOVD)', 'Audio drivers', 'Display drivers'],
        correct_index: 1,
        explanation: 'Bring-Your-Own-Vulnerable-Driver abuses signed kernel drivers.',
        points: 15,
      },
      {
        question: 'Cron jobs running root scripts are exploitable when?',
        options: [
          'The script path is writable by the user',
          'The cron daemon is stopped',
          'The system has no users',
          'Logs are enabled',
        ],
        correct_index: 0,
        explanation: 'A writable cron script runs your edited code as root.',
        points: 15,
      },
      {
        question: 'Which tool automates Linux privesc checks?',
        options: ['LinPEAS', 'Wireshark', 'John', 'Hydra'],
        correct_index: 0,
        explanation: 'LinPEAS enumerates common privilege escalation vectors.',
        points: 10,
      },
    ],
  },
  {
    key: 'cryptography',
    title: 'Cryptography Fundamentals',
    description: 'Hashing, symmetric/asymmetric crypto, and common weaknesses.',
    category: 'cryptography',
    difficulty: 'medium',
    time_limit_minutes: 12,
    pass_threshold: 70,
    questions: [
      {
        question: 'Which algorithm produces a 256-bit hash?',
        options: ['MD5', 'SHA-1', 'SHA-256', 'CRC32'],
        correct_index: 2,
        explanation: 'SHA-256 outputs 256 bits.',
        points: 10,
      },
      {
        question: 'Which attack exploits reused key-stream in stream ciphers?',
        options: ['Birthday attack', 'Nonce reuse', 'Rainbow table', 'Padding oracle'],
        correct_index: 1,
        explanation: 'Reusing a nonce/key-stream reveals XOR relationships between ciphertexts.',
        points: 15,
      },
      {
        question: 'RSA security relies primarily on the difficulty of?',
        options: ['Discrete log', 'Factoring large integers', 'Hash collisions', 'Elliptic curves'],
        correct_index: 1,
        explanation: 'RSA relies on integer factorization hardness.',
        points: 15,
      },
      {
        question: 'Which is a symmetric cipher?',
        options: ['RSA', 'AES', 'Diffie-Hellman', 'ECDSA'],
        correct_index: 1,
        explanation: 'AES uses a shared key; RSA/DH/ECDSA are asymmetric.',
        points: 10,
      },
      {
        question: 'A padding oracle attack targets which mode?',
        options: ['CBC', 'GCM', 'CTR', 'CCM'],
        correct_index: 0,
        explanation: 'CBC with padding validation leaks information (POODLE-style).',
        points: 15,
      },
    ],
  },
  {
    key: 'forensics',
    title: 'Digital Forensics Challenge',
    description: 'Evidence acquisition, memory/disk analysis, and timelines.',
    category: 'forensics',
    difficulty: 'medium',
    time_limit_minutes: 12,
    pass_threshold: 70,
    questions: [
      {
        question: 'Which tool captures volatile memory on Windows?',
        options: ['Volatility (with image)', 'WinDbg', 'Autopsy', 'FTK Imager'],
        correct_index: 0,
        explanation: 'Volatility analyzes memory images; acquisition tools like winpmem capture them.',
        points: 15,
      },
      {
        question: 'Which hash guarantees evidence integrity?',
        options: ['MD5', 'SHA-256', 'CRC32', 'Both MD5 & SHA-256 recommended'],
        correct_index: 3,
        explanation: 'Best practice hashes with two algorithms for integrity verification.',
        points: 10,
      },
      {
        question: 'Where are NTFS file timestamps stored?',
        options: ['$MFT', '$LogFile', '$Bitmap', '$Boot'],
        correct_index: 0,
        explanation: 'The Master File Table ($MFT) holds MACB timestamps.',
        points: 15,
      },
      {
        question: 'Which artifact records USB device history on Windows?',
        options: ['SAM', 'SYSTEM registry (USBSTOR)', 'NTUSER.DAT only', 'pagefile.sys'],
        correct_index: 1,
        explanation: 'USBSTOR keys in the SYSTEM hive record mounted USB devices.',
        points: 15,
      },
      {
        question: 'Plaso/log2timeline is used for?',
        options: ['Disk imaging', 'Timeline creation', 'Password cracking', 'Network capture'],
        correct_index: 1,
        explanation: 'log2timeline/Plaso builds forensic super timelines.',
        points: 10,
      },
    ],
  },
  {
    key: 'reverse-engineering',
    title: 'Malware & Reverse Engineering',
    description: 'Static/dynamic analysis, packing, and obfuscation.',
    category: 'reverse_engineering',
    difficulty: 'hard',
    time_limit_minutes: 15,
    pass_threshold: 70,
    questions: [
      {
        question: 'Which tool is a disassembler/decompiler?',
        options: ['Ghidra', 'Wireshark', 'Nmap', 'Hashcat'],
        correct_index: 0,
        explanation: 'Ghidra disassembles and decompiles binaries.',
        points: 10,
      },
      {
        question: 'UPX is commonly used to?',
        options: ['Compile C code', 'Pack/unpack executables', 'Sign binaries', 'Trace syscalls'],
        correct_index: 1,
        explanation: 'UPX is a common executable packer/unpacker.',
        points: 15,
      },
      {
        question: 'Which Windows API is heavily used by malware for process injection?',
        options: ['CreateProcess', 'VirtualAllocEx + WriteProcessMemory', 'Sleep', 'GetTickCount'],
        correct_index: 1,
        explanation: 'VirtualAllocEx + WriteProcessMemory enable remote memory injection.',
        points: 15,
      },
      {
        question: 'A debugger breakpoint using INT 3 is opcode?',
        options: ['0xCC', '0x90', '0xEB', '0xC3'],
        correct_index: 0,
        explanation: '0xCC (INT 3) is the software breakpoint instruction.',
        points: 15,
      },
      {
        question: 'Which sandbox is widely used for automated malware detonation?',
        options: ['Cuckoo', 'Burp', 'Metasploit', 'John'],
        correct_index: 0,
        explanation: 'Cuckoo Sandbox automates malware analysis runs.',
        points: 10,
      },
    ],
  },
  {
    key: 'osint',
    title: 'OSINT & Reconnaissance',
    description: 'Passive recon, subdomain enumeration, and identity intel.',
    category: 'osint',
    difficulty: 'easy',
    time_limit_minutes: 10,
    pass_threshold: 70,
    questions: [
      {
        question: 'Which record reveals mail servers for a domain?',
        options: ['A', 'MX', 'TXT', 'CNAME'],
        correct_index: 1,
        explanation: 'MX records list mail exchange servers.',
        points: 10,
      },
      {
        question: 'Which tool enumerates subdomains via certificate transparency?',
        options: ['crt.sh', 'Nmap -sV', 'Hydra', 'John'],
        correct_index: 0,
        explanation: 'crt.sh queries certificate transparency logs for subdomains.',
        points: 15,
      },
      {
        question: 'Shodan is best described as?',
        options: ['A password cracker', 'A search engine for internet-connected devices', 'A proxy tool', 'A debugger'],
        correct_index: 1,
        explanation: 'Shodan indexes banners of internet-facing services.',
        points: 10,
      },
      {
        question: 'Which header in HTTP responses can leak server software?',
        options: ['Server', 'Accept', 'Host', 'Referer'],
        correct_index: 0,
        explanation: 'The Server header often discloses web server/version.',
        points: 10,
      },
      {
        question: 'Wayback Machine is useful for?',
        options: ['Cracking hashes', 'Viewing archived historical pages', 'Port scanning', 'Memory analysis'],
        correct_index: 1,
        explanation: 'It archives snapshots of websites over time.',
        points: 15,
      },
    ],
  },
  {
    key: 'security-plus',
    title: 'CompTIA Security+ Practice',
    description: 'Broad certification-style questions across domains.',
    category: 'general',
    difficulty: 'easy',
    time_limit_minutes: 12,
    pass_threshold: 70,
    questions: [
      {
        question: 'The CIA triad stands for?',
        options: [
          'Confidentiality, Integrity, Availability',
          'Control, Identity, Authentication',
          'Cryptography, Integrity, Authorization',
          'Confidentiality, Identity, Access',
        ],
        correct_index: 0,
        explanation: 'Confidentiality, Integrity, and Availability.',
        points: 10,
      },
      {
        question: 'Which control type is a firewall?',
        options: ['Physical', 'Technical', 'Administrative', 'Operational'],
        correct_index: 1,
        explanation: 'A firewall is a technical (logical) control.',
        points: 10,
      },
      {
        question: 'Least privilege means users should have?',
        options: ['No access', 'All access', 'Only the access needed for their role', 'Admin access'],
        correct_index: 2,
        explanation: 'Least privilege grants the minimum access required.',
        points: 15,
      },
      {
        question: 'Which authentication factor is a fingerprint?',
        options: ['Something you know', 'Something you have', 'Something you are', 'Somewhere you are'],
        correct_index: 2,
        explanation: 'Biometrics are "something you are".',
        points: 15,
      },
      {
        question: 'A zero-day vulnerability is one that is?',
        options: [
          'Patched on day zero',
          'Unknown to the vendor with no patch available',
          'Only theoretical',
          'Always low severity',
        ],
        correct_index: 1,
        explanation: 'Zero-day means no vendor patch exists yet.',
        points: 15,
      },
    ],
  },
];